postprocessing:
  - type: template
    template: |+
      name: {{ rule.id }}
      description: {{ rule.title }}
      owner: {{ rule.author }}
     
      type: any
      priority:{% set priority = ({"critical":4, "high":3, "medium":2, "low":1, "informational":0 })%} {{ priority["%s" % rule.level]}}
      alert:
        - debug    
   
      # The Detection Warning miss the index information in the lucene output
      index: linux-*
      filter:
        - query:
            query_string:
              query: '{{ query }}'


finalizers:
  - type: concat