postprocessing:
  - type: template
    template: |+
      name: {{ rule.id }}
      description: {{ rule.title }}
      owner: {{ rule.author }}
     
      type: any
      priority:{% set priority = ({"critical":4, "high":3, "medium":2, "low":1, "informational":0 })%} {{ priority["%s" % rule.level]}}
      alert:
        - debug    
   
      {% macro index() -%}
      {% if rule.logsource.product == 'windows' -%}
      {% if rule.logsource.service == 'application' -%}
      {% set index = 'logs-endpoint-winevent-application-*' -%}
      {% elif rule.logsource.service == 'security' -%}
      {% set index = 'logs-endpoint-winevent-security-*' -%}
      {% elif rule.logsource.category == 'sysmon' or rule.logsource.service == 'sysmon' -%}
      {% set index = 'logs-endpoint-winevent-sysmon-*' -%}
      {% elif rule.logsource.service == 'system' -%}
      {% set index = 'logs-endpoint-winevent-system-*' -%}  
      {% elif rule.logsource.category == 'wmi_event' or rule.logsource.service == 'wmi' -%}
      {% set index = 'logs-endpoint-winevent-wmiactivity-*' -%}
      {% elif rule.logsource.category in ['ps_classic_start','ps_module','ps_script'] or rule.logsource.service in ['powershell','powershell-classic'] -%}
      {% set index = 'logs-endpoint-winevent-powershell-*' -%}
      {% endif -%}
      {% set index = 'logs-endpoint-winevent-*' -%}
      {% elif rule.logsource.product == 'linux' -%}
      {% set index = 'linux-*' -%}
      {% else -%}
      {% set index = 'logs-*' -%}
      {% endif -%}
      {{- index }}{% endmacro -%}
      index: {{ index() }}
      filter:
        - query:
            query_string:
              query: '{{ query }}'


finalizers:
  - type: concat