version: '3.5'

services:
  helk-base:
    build: helk-base/
    container_name: helk-base
    build: helk-nginx/
    container_name: helk-nginx
    logging:
      driver: "json-file"
      options:
        max-file: "9"
        max-size: "6m"
    secrets:
      - source: htpasswd.users
        target: /etc/nginx/htpasswd.users
    volumes:
      - ./helk-nginx/config/basic-helk:/etc/nginx/conf.d/default.conf
      - ./helk-nginx/scripts/:/opt/helk/scripts/
    entrypoint: /opt/helk/scripts/nginx-entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - helk-kibana
    networks:
      helk:
  helk-kafka-base:
    build: helk-kafka-base/
    container_name: helk-kafka-base
    depends_on:
      - helk-base
  helk-jupyter-base:
    build: helk-jupyter-base/
    container_name: helk-jupyter-base
        environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    restart: always
    networks:
      helk:
  helk-jupyter-pyspark:
    build: helk-jupyter-pyspark/
    container_name: helk-jupyter-pyspark
    environment:
      JUPYTER_TYPE: notebook
      JUPYTER_BASE_URL: /jupyter
    restart: always
    networks:
      helk:
  helk-jupyter-hunt:
    build: helk-jupyter-hunt/
    container_name: helk-jupyter-hunt
    volumes:
      - notebooks:/opt/jupyter/notebooks
    environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
    restart: always
    networks:
      helk:
  helk-spark-base:
    build: helk-spark-base/
    container_name: helk-spark-base
    depends_on:
      - helk-base

networks:
  helk:
    driver: bridge

volumes:
  esdata:
    driver: local
  notebooks:
    driver: local
